version: '2'

networks:
    LEMP:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.57.0/24

services:
    nginx:
        image: nginx:stable-alpine
        container_name: LEMP_nginx
        ports:
            - "8080:80"
        volumes:
            - ./www:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - LEMP
        restart: on-failure

    mariaDB:
        image: mariadb:10.10
        container_name: LEMP_mariaDB
        volumes:
            - ./database:/var/lib/mysql:rw
        depends_on:
            - nginx
        env_file:
            - ./.mysql.env
        networks:
            - LEMP
        restart: on-failure

    php:
        image: chialab/php:7.4-fpm
        container_name: LEMP_php
        volumes:
            - ./www:/code
        networks:
            - LEMP
        restart: on-failure

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: LEMP_phpMyAdmin
        ports:
            - "8183:80"
        environment:
            PMA_HOST: LEMP_mariaDB
        depends_on:
            - mariaDB
        networks:
            - LEMP
        restart: on-failure
